name: PR

on:
  workflow_dispatch:
  pull_request:
    branches: [ master, develop ]

jobs:
  check:
    name: PR
   
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: 🤖 Setup LCOV
        uses: hrishikesh-kadam/setup-lcov@v1
          
      - name: 💩 Setup node 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          
      - name: 💩 Install node-html-parser
        run: npm install --save-dev node-html-parser

      - name: 💩 Install node-fetch
        run: npm install --save-dev node-fetch  
        
      - name: 🧪 Test lines
        run: npm test

      - name: 🧪 Test coverage
        run: npm coverage
             
      - name: 🎉 Send metrics to server
        run: node metric.js
